apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ./guestbook-frontend.deployment-patch.yaml
- ./guestbook-frontend.service-patch.yaml

resources:
- ../../base/

images:
- name: ahmedulde/guestbook-frontend-demo
  newTag: 14b54538c57d6e5bceec3801ae40e48df0b642e7
